### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by hsiaoyi0504**
Update documents based on my installation steps of django-blast (On CentOS 7.2). Old setup guide is renamed but kept in repo. Another thing is that the `sphinx_doc/_build/` directory should be removed through `git filter-branch`.

### CODE REVIEW

**Review by childers — COMMENTED** [review]
How will this affect the readthedocs site: http://genomics-workspace.readthedocs.io/en/latest/index.html

**Comment by childers** [comment]
How will this affect the readthedocs site?
http://genomics-workspace.readthedocs.io/en/latest/index.html

**Comment by hsiaoyi0504** [comment]
I think it will not affect http://genomics-workspace.readthedocs.io/en/latest/index.html
but will affect http://django-blast.readthedocs.io/en/latest/index.html.

@ifishlin told me that it will automatically build a new document from this repo.

I just moved the original doc for CentOS6.* to other place, but it still can be accessed through link in setup_guide.

**Comment by childers** [comment]
Great, thanks for confirming.

**Comment by childers** [comment]
@hsiaoyi0504 I just realized this is not on the current fork. We've moved active development to this repository: 
https://github.com/NAL-i5K/genomics-workspace

**Comment by hsiaoyi0504** [comment]
Ok, thanks for notifying me this! I will make another PR there.

**Pull request closed without merging**
